=== pzsolt72/lwi/ConfigSamples/LwiConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://telekom.hu/LwiConfiguration"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://telekom.hu/LwiConfiguration">

	<complexType name="LwiConfiguration">
		<sequence>
			<element name="log" type="tns:LwiLog" minOccurs="1"
				maxOccurs="1">
			</element>
			<element name="consumers" minOccurs="1" maxOccurs="1">
				<complexType>
					<sequence>
						<element name="consumerApplication" type="tns:LwiConsumer"
							minOccurs="0" maxOccurs="unbounded">
						</element>
					</sequence>
				</complexType>
			</element>
			<element name="providers" minOccurs="1" maxOccurs="1">
				<complexType>
					<sequence>
						<element name="provider" type="tns:LwiProvider" minOccurs="0"
							maxOccurs="unbounded"></element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<complexType name="LwiLog">
		<sequence>
			<element name="detail" minOccurs="1" maxOccurs="1">
				<simpleType>
					<restriction base="string">
						<enumeration value="FULL"></enumeration>
						<enumeration value="CTX"></enumeration>
						<enumeration value="MIN"></enumeration>
					</restriction>
				</simpleType>
			</element>
		</sequence>
	</complexType>

	<complexType name="LwiConsumer">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1">
			</element>
			<element name="password" type="string" minOccurs="0"
				maxOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="LwiService">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1">
			</element>
			<element name="businessService" type="string" minOccurs="1"
				maxOccurs="1">
			</element>
			<element name="validationType" minOccurs="1" maxOccurs="1">
				<simpleType>
					<restriction base="string">
						<enumeration value="CTX"></enumeration>
						<enumeration value="MSG"></enumeration>
						<enumeration value="NO"></enumeration>
					</restriction>
				</simpleType>
			</element>
			<element name="maxRequests" type="int" minOccurs="1"
				maxOccurs="1">
			</element>
			<element name="requestQueueLength" type="int" minOccurs="1"
				maxOccurs="1">
			</element>
			<element name="allowedConsumers">
				<complexType>
					<sequence>
						<element name="consumerName" type="string" minOccurs="0"
							maxOccurs="unbounded"></element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<element name="lwiConfiguration" type="tns:LwiConfiguration"></element>

    <complexType name="LwiProvider">
        							<sequence>
    								<element name="name"
    									type="string" minOccurs="1" maxOccurs="1">
    								</element>
    								<element name="loadBalancerHost"
    									type="string" minOccurs="1" maxOccurs="1">
    								</element>
    								<element name="loadBalancerPort"
    									type="int" minOccurs="1" maxOccurs="1">
    								</element>
    								<element name="protocol" minOccurs="1" maxOccurs="1">
    									<simpleType>
    										<restriction
    											base="string">
    											<enumeration
    												value="http">
    											</enumeration>
    											<enumeration
    												value="https">
    											</enumeration>
    										</restriction>
    									</simpleType>
    								</element>
    								    		<element name="services" minOccurs="1" maxOccurs="1">
    			<complexType>
    				<sequence>
    					<element name="service" type="tns:LwiService"
    						minOccurs="0" maxOccurs="unbounded">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    								
    							</sequence>
    </complexType>
</schema>

=== pzsolt72/lwi/ConfigSamples/LwiConfiguration3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:lwiConfiguration xmlns:tns="http://telekom.hu/LwiConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://telekom.hu/LwiConfiguration LwiConfiguration.xsd ">
  <tns:log>
    <tns:detail>FULL</tns:detail>
  </tns:log>
  <tns:consumers>
    <tns:consumerApplication>
      <tns:name>mami</tns:name>
      <tns:password>12345</tns:password>
    </tns:consumerApplication>
  </tns:consumers>
  <tns:providers>
    <tns:provider>
      <tns:name>cnr</tns:name>
      <tns:loadBalancerHost>shark-dev</tns:loadBalancerHost>
      <tns:loadBalancerPort>17001</tns:loadBalancerPort>
      <tns:protocol>https</tns:protocol>
      <tns:services>
        <tns:service>
          <tns:name>getMsisdn</tns:name>
          <tns:businessService>cnrservice/getmsidn</tns:businessService>
          <tns:validationType>CTX</tns:validationType>
          <tns:maxRequests>20</tns:maxRequests>
          <tns:requestQueueLength>40</tns:requestQueueLength>
          <tns:allowedConsumers/>
        </tns:service>
      </tns:services>
    </tns:provider>
  </tns:providers>
</tns:lwiConfiguration>

=== pzsolt72/lwi/lwi-wildflyplugin/samples/LwiConfiguration2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:lwiConfiguration xmlns:tns="http://telekom.hu/LwiConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://telekom.hu/LwiConfiguration LwiConfiguration.xsd ">
  <tns:log>
    <tns:detail>FULL</tns:detail>
  </tns:log>
  <tns:consumers>
    <tns:consumerApplication>
      <tns:name>tns:name</tns:name>
    </tns:consumerApplication>
  </tns:consumers>
  <tns:providers>
    <tns:provider>
      <tns:name>tns:name</tns:name>
      <tns:loadBalancerHost>tns:loadBalancerHost</tns:loadBalancerHost>
      <tns:loadBalancerPort>0</tns:loadBalancerPort>
      <tns:protocol>http</tns:protocol>
      <tns:services/>
    </tns:provider>
  </tns:providers>
</tns:lwiConfiguration>

=== pzsolt72/lwi/lwi-wildflyplugin/samples/LwiConfiguration4.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:lwiConfiguration xmlns:tns="http://telekom.hu/LwiConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://telekom.hu/LwiConfiguration LwiConfiguration.xsd ">
  <tns:log>
    <tns:detail>FULL</tns:detail>
  </tns:log>
  <tns:consumers>
    <tns:consumerApplication>
      <tns:name>tns:name</tns:name>
      <tns:password>tns:password</tns:password>
    </tns:consumerApplication>
  </tns:consumers>
  <tns:providers>
    <tns:provider>
      <tns:name>tns:name</tns:name>
      <tns:loadBalancerHost>tns:loadBalancerHost</tns:loadBalancerHost>
      <tns:loadBalancerPort>0</tns:loadBalancerPort>
      <tns:protocol>http</tns:protocol>
      <tns:services>
        <tns:service>
          <tns:name>tns:name</tns:name>
          <tns:businessService>tns:businessService</tns:businessService>
          <tns:validationType>CTX</tns:validationType>
          <tns:maxRequests>0</tns:maxRequests>
          <tns:requestQueueLength>0</tns:requestQueueLength>
          <tns:allowedConsumers>
            <tns:consumerName>tns:consumerName</tns:consumerName>
          </tns:allowedConsumers>
        </tns:service>
      </tns:services>
    </tns:provider>
  </tns:providers>
</tns:lwiConfiguration>
